version: '3.2'
services:
  master:
    image: salt-master
    build: .
    volumes:
      # - /data/salt-master/master.d:/etc/salt/master.d
      # - /data/salt-master/pki:/etc/salt/pki
      # - /data/salt-master/cache:/var/cache/salt
      # - /data/salt-master/log:/var/log/salt
      - ../salt-master-vols/protos/master.d:/etc/salt/master.d
      - ../salt-master-vols/protos/pki:/etc/salt/pki
      - ../salt-master-vols/protos/cache:/var/cache/salt
      - ../salt-master-vols/protos/log:/var/log/salt
    ports:
      - published: 4505
        target: 4505
        mode: host
      - published: 4506
        target: 4506
        mode: host
